# Generated by Django 6.0 on 2026-01-02 12:34

import conciliacion_app.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCargado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(choices=[('NOMINA', 'Nómina RRHH (Excel)'), ('AD', 'Active Directory (TXT)')], max_length=20)),
                ('archivo', models.FileField(upload_to=conciliacion_app.models.archivo_upload_path)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('errores', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Cargado',
                'verbose_name_plural': 'Archivos Cargados',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='CuentaActiveDirectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(db_index=True, max_length=20)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado_cuenta', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('BLOQUEADA', 'Bloqueada'), ('DESHABILITADA', 'Deshabilitada')], max_length=20)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_ad', to='conciliacion_app.archivocargado')),
            ],
            options={
                'verbose_name': 'Cuenta Active Directory',
                'verbose_name_plural': 'Cuentas Active Directory',
                'ordering': ['nombre_usuario'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('estado_final', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('CONFLICTO', 'Conflicto de estados')], max_length=20)),
                ('registros_originales', models.IntegerField(default=1)),
                ('tiene_conflicto', models.BooleanField(default=False)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_nomina', to='conciliacion_app.archivocargado')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(db_index=True, max_length=20)),
                ('categoria', models.CharField(choices=[('FANTASMA_TOTAL', 'Fantasma Total - No existe en RRHH'), ('INACTIVO_CON_CUENTA', 'Inactivo con cuenta AD activa'), ('CONFLICTO_REVISION', 'Conflicto - Requiere revisión manual'), ('OK_ACTIVO', 'OK - Activo con cuenta'), ('OK_INACTIVO', 'OK - Inactivo sin cuenta')], max_length=30)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja'), ('NINGUNA', 'Ninguna')], max_length=20)),
                ('accion_recomendada', models.CharField(choices=[('ELIMINAR_CUENTA', 'Eliminar cuenta AD'), ('BLOQUEAR_CUENTA', 'Bloquear cuenta AD'), ('REVISION_MANUAL', 'Revisión manual requerida'), ('MANTENER', 'Mantener situación actual')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_deteccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_resueltas', to=settings.AUTH_USER_MODEL)),
                ('cuenta_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='conciliacion_app.cuentaactivedirectory')),
                ('empleado_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='conciliacion_app.empleadonomina')),
            ],
            options={
                'verbose_name': 'Conciliación',
                'verbose_name_plural': 'Conciliaciones',
                'ordering': ['prioridad', '-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoConciliacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('total_empleados', models.IntegerField(default=0)),
                ('total_cuentas_ad', models.IntegerField(default=0)),
                ('conciliaciones_generadas', models.IntegerField(default=0)),
                ('fantasmas_totales', models.IntegerField(default=0)),
                ('inactivos_con_cuenta', models.IntegerField(default=0)),
                ('conflictos_revision', models.IntegerField(default=0)),
                ('ok_activos', models.IntegerField(default=0)),
                ('ok_inactivos', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='INICIADO', max_length=20)),
                ('errores', models.TextField(blank=True, null=True)),
                ('archivo_ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_como_ad', to='conciliacion_app.archivocargado')),
                ('archivo_nomina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_como_nomina', to='conciliacion_app.archivocargado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Conciliación',
                'verbose_name_plural': 'Procesos de Conciliación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ScriptPowershell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_script', models.CharField(choices=[('BLOQUEO_MASIVO', 'Bloqueo masivo de cuentas'), ('REPORTE', 'Reporte informativo'), ('ROLLBACK', 'Reversión de cambios')], max_length=30)),
                ('contenido', models.TextField()),
                ('modo_seguro', models.BooleanField(default=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('ejecutado', models.BooleanField(default=False)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('resultado_ejecucion', models.TextField(blank=True, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='conciliacion_app.procesoconciliacion')),
                ('usuario_generacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Script PowerShell',
                'verbose_name_plural': 'Scripts PowerShell',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddIndex(
            model_name='cuentaactivedirectory',
            index=models.Index(fields=['estado_cuenta'], name='conciliacio_estado__4e7b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadonomina',
            index=models.Index(fields=['estado_final'], name='conciliacio_estado__a66778_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadonomina',
            index=models.Index(fields=['tiene_conflicto'], name='conciliacio_tiene_c_e8b2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacion',
            index=models.Index(fields=['categoria'], name='conciliacio_categor_c34200_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacion',
            index=models.Index(fields=['resuelto'], name='conciliacio_resuelt_9ddfda_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacion',
            index=models.Index(fields=['prioridad', 'resuelto'], name='conciliacio_priorid_6eb752_idx'),
        ),
    ]
