# Generated by Django 6.0 on 2026-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadonomina',
            name='rut',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
